### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement ansio==0.0.2 (from versions: none) ERROR: No matching distribution found for ansio==0.0.2

### ISSUE THREAD

**Issue by MrQwenty** [nineteendo/ansio#3]
ERROR: No matching distribution found for ansio==0.0.2

**Comment by nineteendo** [comment]
Could you provide more information?

**Comment by MrQwenty** [comment]
It turns out impossible to install it in a python project, I tried the command with Pip as described but it doesn't work

**Comment by nineteendo** [comment]
That's very strange because `pip install ansio==0.0.2` works for me.

**Comment by MrQwenty** [comment]
![Screenshot 2024-08-07 alle 09 13 09](https://github.com/user-attachments/assets/576497bb-206d-4ff6-b33f-e87566252104)

**Comment by MrQwenty** [comment]
the problem was related to the fact that some packages required a version of python 3.10 or higher, and now I finally solved it, thanks anyway for the timely support!
